import Link from 'next/link'
import { CalendarDays, Clock3, Users } from 'lucide-react'
import { getMyEventReservations } from '../../../../lib/eventReservations'
import { formatDate } from '../../../../lib/format'

const labels: Record<string,string> = { pending:'Awaiting reception', reserved:'Reserved', declined:'Not available', cancelled:'Cancelled' }
export default async function EventReservationsPage() {
  const reservations = await getMyEventReservations()
  return <div><div className="mb-7"><span className="eyebrow">Events</span><h1 className="text-3xl font-semibold mt-2">My event reservations</h1><p className="text-sm text-navy-500 mt-2">Track every event request from the moment you submit it until reception confirms your spot.</p></div>
    {reservations.length===0 ? <div className="card p-9 text-center"><CalendarDays size={28} className="mx-auto text-gold-500 mb-3"/><h2 className="font-semibold text-lg">No event reservations yet</h2><p className="text-sm text-navy-400 mt-2 mb-5">Find an upcoming event and request your spot.</p><Link href="/events" className="btn-primary">Explore events</Link></div> : <div className="grid gap-5">{reservations.map(r=><div key={r.id} className="card overflow-hidden"><div className="flex flex-col md:flex-row">{r.event?.image&&<img src={r.event.image} alt={r.event.title} className="w-full md:w-56 h-48 md:h-auto object-cover"/>}<div className="p-6 flex-1"><div className="flex items-start justify-between gap-3"><div><span className="tag">{r.event?.title||'Event'}</span><h2 className="font-display text-2xl mt-3">{r.event?.title}</h2></div><span className={r.status==='reserved'?'pill-green':r.status==='declined'?'pill-red':'pill-amber'}>{labels[r.status]||r.status}</span></div><div className="grid sm:grid-cols-3 gap-3 mt-5 text-sm"><div className="flex gap-2 items-center"><CalendarDays size={15} className="text-gold-500"/>{r.event?.date ? formatDate(r.event.date) : '—'}</div><div className="flex gap-2 items-center"><Users size={15} className="text-gold-500"/>{r.guest_count} guest{r.guest_count===1?'':'s'}</div><div className="flex gap-2 items-center"><Clock3 size={15} className="text-gold-500"/>Requested {new Date(r.created_at).toLocaleDateString('en-NG')}</div></div>{r.notes&&<p className="text-sm text-navy-500 bg-cream-100 rounded-lg p-3 mt-5"><b>Your note:</b> {r.notes}</p>}{r.staff_note&&<p className="text-sm text-navy-600 bg-blue-50 rounded-lg p-3 mt-3"><b>Reception:</b> {r.staff_note}</p>}<p className="text-[11px] text-navy-400 mt-5">Request ID: {r.id}</p></div></div></div>)}</div>}
  </div>
}
