'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { CheckCircle2, ChevronLeft, Clock3, FileText, Image as ImageIcon, Loader2, MessageSquare, Paperclip, Send, ShieldCheck, X } from 'lucide-react'

type Conversation = { id: string; subject: string; category: string; status: string; priority: string; guest_name: string; last_message_at: string; created_at: string }
type Message = { id: string; sender_type: 'guest' | 'staff'; message: string; created_at: string; attachment_url?: string | null; attachment_name?: string | null; attachment_mime_type?: string | null; attachment_size?: number | null }
const statusLabel: Record<string, string> = { open: 'Open', waiting_for_staff: 'Waiting for our team', waiting_for_guest: 'Waiting for your reply', resolved: 'Resolved' }
function formatDate(value: string) { return new Date(value).toLocaleString('en-NG', { dateStyle: 'medium', timeStyle: 'short' }) }
function formatSize(size?: number | null) { if (!size) return ''; if (size < 1024 * 1024) return `${Math.round(size / 1024)} KB`; return `${(size / 1024 / 1024).toFixed(1)} MB` }
function isImage(message: Message) { return !!message.attachment_mime_type?.startsWith('image/') }

export default function MessagesPage() {
  const searchParams = useSearchParams(), requestedId = searchParams.get('conversation'), fileRef = useRef<HTMLInputElement>(null)
  const [conversations, setConversations] = useState<Conversation[]>([]), [selectedId, setSelectedId] = useState(requestedId || ''), [messages, setMessages] = useState<Message[]>([]), [selected, setSelected] = useState<Conversation | null>(null)
  const [reply, setReply] = useState(''), [file, setFile] = useState<File | null>(null), [loading, setLoading] = useState(true), [detailLoading, setDetailLoading] = useState(false), [sending, setSending] = useState(false), [error, setError] = useState(''), [lightbox, setLightbox] = useState<string | null>(null)

  async function loadConversations(preferredId?: string) { setLoading(true); setError(''); try { const response = await fetch('/api/contact/conversations', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load messages.'); const list = data.conversations || []; setConversations(list); const nextId = preferredId || selectedId || list[0]?.id || ''; setSelectedId(nextId); if (nextId) await loadConversation(nextId) } catch (e: any) { setError(e?.message || 'Unable to load messages.') } finally { setLoading(false) } }
  async function loadConversation(id: string) { setDetailLoading(true); setError(''); try { const response = await fetch(`/api/contact/conversations/${id}`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load the conversation.'); setSelected(data.conversation); setMessages(data.messages || []); setConversations(current => current.map(item => item.id === id ? { ...item, ...data.conversation } : item)) } catch (e: any) { setError(e?.message || 'Unable to load the conversation.') } finally { setDetailLoading(false) } }
  useEffect(() => { loadConversations(requestedId || undefined) }, [])
  const sorted = useMemo(() => [...conversations].sort((a, b) => +new Date(b.last_message_at) - +new Date(a.last_message_at)), [conversations])
  async function sendReply() { if (!selectedId || (!reply.trim() && !file)) return; setSending(true); setError(''); try { const form = new FormData(); form.append('message', reply.trim()); if (file) form.append('file', file); const response = await fetch(`/api/contact/conversations/${selectedId}`, { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to send your reply.'); setReply(''); setFile(null); if (fileRef.current) fileRef.current.value = ''; await loadConversation(selectedId) } catch (e: any) { setError(e?.message || 'Unable to send your reply.') } finally { setSending(false) } }

  return <div className="space-y-6">
    <div><p className="text-xs uppercase tracking-[0.22em] text-blue-700 font-semibold">Guest communication</p><h1 className="text-2xl md:text-3xl font-semibold text-slate-950 mt-1">Messages</h1><p className="text-slate-500 mt-2">Keep track of your conversations with the Blue Pair Hotel team.</p></div>
    {error && <div className="rounded-xl border border-red-100 bg-red-50 text-red-700 p-3 text-sm">{error}</div>}
    <div className="grid lg:grid-cols-[330px_1fr] gap-5 min-h-[620px]">
      <aside className={`${selectedId ? 'hidden lg:block' : 'block'} rounded-2xl border border-slate-200 bg-white overflow-hidden`}><div className="p-4 border-b border-slate-100 flex items-center justify-between"><div><p className="font-semibold text-slate-900">Your conversations</p><p className="text-xs text-slate-500 mt-0.5">{sorted.length} conversation{sorted.length === 1 ? '' : 's'}</p></div><MessageSquare size={18} className="text-blue-700" /></div>{loading ? <div className="p-8 text-center text-slate-500"><Loader2 className="animate-spin mx-auto" size={22} /></div> : sorted.length === 0 ? <div className="p-8 text-center"><MessageSquare size={28} className="mx-auto text-slate-300" /><p className="font-medium mt-3 text-slate-700">No messages yet</p><p className="text-sm text-slate-500 mt-1">Start a conversation from the Contact page.</p></div> : <div className="divide-y divide-slate-100">{sorted.map(item => <button key={item.id} onClick={() => { setSelectedId(item.id); loadConversation(item.id) }} className={`w-full text-left p-4 hover:bg-slate-50 transition ${selectedId === item.id ? 'bg-blue-50/70' : ''}`}><div className="flex items-start justify-between gap-3"><p className="font-semibold text-sm text-slate-900 truncate">{item.subject}</p>{item.priority === 'urgent' && <span className="text-[10px] font-semibold text-red-600">URGENT</span>}</div><p className="text-xs text-slate-500 mt-1">{item.category}</p><div className="flex items-center gap-1.5 mt-2 text-xs text-slate-400"><Clock3 size={12} />{formatDate(item.last_message_at)}</div><span className="inline-flex mt-2 rounded-full bg-slate-100 px-2 py-1 text-[11px] text-slate-600">{statusLabel[item.status] || item.status}</span></button>)}</div>}</aside>
      <section className={`${selectedId ? 'block' : 'hidden lg:block'} rounded-2xl border border-slate-200 bg-white overflow-hidden flex flex-col`}>
        {!selected ? <div className="flex-1 grid place-items-center p-10 text-center"><div><MessageSquare size={36} className="mx-auto text-slate-300" /><p className="font-semibold text-slate-700 mt-3">Select a conversation</p><p className="text-sm text-slate-500 mt-1">Your conversation history will appear here.</p></div></div> : <>
          <div className="p-4 md:p-5 border-b border-slate-100"><button onClick={() => setSelectedId('')} className="lg:hidden inline-flex items-center gap-1 text-sm text-blue-700 mb-3"><ChevronLeft size={16} />Back</button><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-blue-700 font-semibold">{selected.category}</p><h2 className="text-lg md:text-xl font-semibold text-slate-950 mt-1">{selected.subject}</h2><p className="text-xs text-slate-500 mt-1">Started {formatDate(selected.created_at)}</p></div><span className="rounded-full bg-blue-50 text-blue-700 px-3 py-1 text-xs font-semibold">{statusLabel[selected.status] || selected.status}</span></div></div>
          <div className="flex-1 p-4 md:p-6 space-y-4 overflow-y-auto min-h-[420px] bg-slate-50/50">{detailLoading ? <div className="grid place-items-center h-full"><Loader2 className="animate-spin text-blue-700" size={24} /></div> : messages.map(message => <div key={message.id} className={`flex ${message.sender_type === 'guest' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[86%] md:max-w-[72%] rounded-2xl px-4 py-3 ${message.sender_type === 'guest' ? 'bg-blue-700 text-white rounded-br-md' : 'bg-white border border-slate-200 text-slate-800 rounded-bl-md shadow-sm'}`}><div className={`text-[11px] font-semibold mb-1 ${message.sender_type === 'guest' ? 'text-blue-100' : 'text-blue-700'}`}>{message.sender_type === 'guest' ? 'You' : 'Blue Pair Hotel'}</div>{message.attachment_url && (isImage(message) ? <button onClick={() => setLightbox(message.attachment_url || null)} className="block mb-2 overflow-hidden rounded-xl bg-black/5"><img loading="lazy" decoding="async" src={message.attachment_url} alt={message.attachment_name || 'Attachment'} className="block max-w-[240px] sm:max-w-[280px] max-h-[240px] object-cover" /></button> : <a href={message.attachment_url} target="_blank" rel="noreferrer" className={`mb-2 flex max-w-[280px] items-center gap-3 rounded-xl border p-3 ${message.sender_type === 'guest' ? 'border-white/20 bg-white/10' : 'border-slate-200 bg-slate-50'}`}><FileText size={22} className="shrink-0" /><span className="min-w-0 text-left"><span className="block truncate text-xs font-semibold">{message.attachment_name}</span><span className={`block text-[10px] ${message.sender_type === 'guest' ? 'text-blue-100' : 'text-slate-400'}`}>{formatSize(message.attachment_size)}</span></span></a>)}{message.message && <p className="text-sm leading-6 whitespace-pre-wrap">{message.message}</p>}<p className={`text-[10px] mt-2 ${message.sender_type === 'guest' ? 'text-blue-100' : 'text-slate-400'}`}>{formatDate(message.created_at)}</p></div></div>)}</div>
          {selected.status !== 'resolved' ? <div className="p-3 md:p-4 border-t border-slate-100 bg-white"><input ref={fileRef} type="file" accept="image/*,.pdf,.txt,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.zip" className="hidden" onChange={e => setFile(e.target.files?.[0] || null)} /><div className="flex items-end gap-2"><button type="button" onClick={() => fileRef.current?.click()} className="h-11 w-11 shrink-0 rounded-xl border border-slate-200 bg-white text-slate-600 hover:bg-slate-50 inline-grid place-items-center" aria-label="Attach image or file"><Paperclip size={18} /></button><textarea value={reply} onChange={e => setReply(e.target.value)} rows={2} maxLength={5000} onKeyDown={e => { if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') sendReply() }} className="field-input flex-1 !h-auto resize-none" placeholder="Write a reply…" /><button disabled={sending || (!reply.trim() && !file)} onClick={sendReply} className="btn-primary h-11 px-4 disabled:opacity-50 inline-flex items-center gap-2">{sending ? <Loader2 size={16} className="animate-spin" /> : <Send size={16} />}<span className="hidden sm:inline">Send</span></button></div>{file && <div className="mt-2 flex items-center gap-2 rounded-xl bg-slate-50 border border-slate-200 px-3 py-2 text-xs"><ImageIcon size={15} className="text-blue-700 shrink-0" /><span className="truncate flex-1">{file.name}</span><span className="text-slate-400 shrink-0">{formatSize(file.size)}</span><button type="button" onClick={() => { setFile(null); if (fileRef.current) fileRef.current.value = '' }} className="text-slate-400 hover:text-red-600" aria-label="Remove attachment"><X size={15} /></button></div>}<p className="text-[11px] text-slate-400 mt-2">Attach an image or file up to 15 MB. Images stay compact in the conversation.</p></div> : <div className="p-4 border-t border-slate-100 bg-slate-50 flex items-center gap-2 text-sm text-slate-600"><CheckCircle2 size={17} className="text-emerald-600" />This conversation has been resolved. Start a new conversation if you need more help.</div>}
        </>}
      </section>
    </div>
    {lightbox && <div className="fixed inset-0 z-[100] h-dvh min-h-screen w-screen overflow-hidden bg-black/[0.92] backdrop-blur-2xl p-4 grid place-items-center" onClick={() => setLightbox(null)}><button className="absolute top-4 right-4 z-10 h-10 w-10 rounded-full bg-white/10 text-white grid place-items-center" onClick={() => setLightbox(null)} aria-label="Close image"><X /></button><img src={lightbox} alt="Attachment preview" className="max-h-[88dvh] max-w-[92vw] object-contain rounded-xl" onClick={e => e.stopPropagation()} /></div>}
  </div>
}
