'use client'
import {useEffect,useMemo,useState} from 'react'
import {ChevronLeft,ChevronRight,CalendarDays} from 'lucide-react'
import {addDaysISO,todayISO} from '../../lib/format'

type Day={date:string;status:'available'|'booked'|'held'|'occupied'|'availableSoon';reference?:string|null;source?:string|null;check_in?:string|null;check_out?:string|null}
function monthStart(v:string){return `${v.slice(0,7)}-01`}
function monthLabel(v:string){return new Date(`${v}T00:00:00`).toLocaleDateString('en-NG',{month:'long',year:'numeric'})}
function pad(n:number){return String(n).padStart(2,'0')}
function daysInMonth(v:string){const d=new Date(`${v}T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);return d.getUTCDate()}
function dayOfWeek(v:string){return new Date(`${v}T00:00:00Z`).getUTCDay()}
export default function AvailabilityCalendar({roomId,initialCheckIn,initialCheckOut,onSelect}:{roomId:string;initialCheckIn?:string;initialCheckOut?:string;onSelect?:(checkIn:string,checkOut:string)=>void}){
 const [month,setMonth]=useState(monthStart(initialCheckIn||todayISO()));const [days,setDays]=useState<Day[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [start,setStart]=useState(initialCheckIn||'');const [end,setEnd]=useState(initialCheckOut||'')
 useEffect(()=>{let cancelled=false;const from=month;const to=addDaysISO(1,`${month.slice(0,7)}-${pad(daysInMonth(month))}`);setLoading(true);fetch(`/api/public/room-calendar?roomId=${encodeURIComponent(roomId)}&from=${from}&to=${to}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>{if(cancelled)return;if(data?.days){setDays(data.days);setError(null)}else setError(data?.error||'Unable to load calendar.')}).catch(()=>{if(!cancelled)setError('Unable to load calendar.')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[roomId,month])
 const cells=useMemo(()=>{const blanks=Array.from({length:dayOfWeek(month)}).map((_,i)=>({blank:i}));return [...blanks,...days]},[month,days])
 function choose(date:string,status:Day['status']){if(status!=='available')return;if(!start||end){setStart(date);setEnd('');return}if(date<=start){setStart(date);setEnd('');return}setEnd(date);onSelect?.(start,date)}
 return <div className="rounded-2xl border border-black/[0.07] bg-white p-4 sm:p-5 shadow-sm"><div className="flex items-center justify-between mb-4"><div><div className="flex items-center gap-2"><CalendarDays size={15} className="text-gold-600"/><h3 className="text-sm font-semibold">Room availability</h3></div><p className="text-[10px] text-navy-400 mt-1">Check-in 3:00 PM · Check-out 12:00 PM</p></div><div className="flex gap-1"><button type="button" onClick={()=>{const d=new Date(`${month}T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()-1);setMonth(`${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-01`)}} className="w-7 h-7 rounded-lg border border-black/10 flex items-center justify-center"><ChevronLeft size={14}/></button><button type="button" onClick={()=>{const d=new Date(`${month}T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+1);setMonth(`${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-01`)}} className="w-7 h-7 rounded-lg border border-black/10 flex items-center justify-center"><ChevronRight size={14}/></button></div></div><div className="text-center text-xs font-semibold mb-3">{monthLabel(month)}</div><div className="grid grid-cols-7 gap-1 mb-2">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><span key={x} className="text-center text-[9px] uppercase tracking-wider text-navy-400">{x.slice(0,2)}</span>)}</div><div className="grid grid-cols-7 gap-1">{cells.map((cell:any,i:number)=>cell.blank!==undefined?<span key={`blank-${i}`} className="h-9 sm:h-10"/>:<button key={cell.date} type="button" disabled={cell.status!=='available'} onClick={()=>choose(cell.date,cell.status)} title={cell.status==='booked'?`Booked${cell.reference?` · ${cell.reference}`:''}`:cell.status==='held'?'Temporarily held':cell.status==='availableSoon'?'Unavailable due to room condition':'Available'} className={'h-9 sm:h-10 rounded-lg text-[10px] font-semibold border transition '+(cell.date===start||cell.date===end?'bg-navy-950 text-white border-navy-950':cell.status==='available'?'bg-emerald-50 text-emerald-700 border-emerald-100 hover:bg-emerald-100':cell.status==='booked'?'bg-red-50 text-red-600 border-red-100 cursor-not-allowed':cell.status==='held'?'bg-amber-50 text-amber-700 border-amber-100 cursor-not-allowed':'bg-navy-50 text-navy-400 border-transparent cursor-not-allowed')}>{Number(cell.date.slice(-2))}</button>)}</div>{loading&&<p className="text-[10px] text-navy-400 mt-3 text-center">Loading availability…</p>}{error&&<p className="text-[10px] text-red-600 mt-3 text-center">{error}</p>}<div className="flex flex-wrap gap-3 mt-4 pt-3 border-t border-black/[0.07] text-[9px] text-navy-500"><span>🟢 Available</span><span>🔴 Booked</span><span>🟡 Held</span><span>⚫ Unavailable</span></div>{start&&end&&<p className="text-[10px] text-navy-500 mt-3 text-center">Selected: <b>{start}</b> → <b>{end}</b></p>}</div>
}
