import { create } from 'zustand'
import { supabase } from '../lib/supabase/client'
import {
  mapRoomType, mapRoom, mapBooking, mapCustomer, mapStaff, mapMenuItem, mapDrink,
  mapShortLet, mapEvent, mapMaintenanceTicket, mapHousekeepingTask, mapBillboard,
  mapParkingZone, mapPayment, mapOffer, mapGuestRequest, type GuestRequest,
  mapGalleryImage, type GalleryImage, mapAmenity, type Amenity,
} from '../lib/mappers'
import { type RoomType, type Room, type Booking, type Customer, type StaffMember, type MenuItem, type Drink, type ShortLet, type EventItem, type MaintenanceTicket, type HousekeepingTask, type BillboardSpace, type Payment, type Offer, type RoomStatus, type ParkingZone } from '../data/mock'
import { ROLE_LABEL_TO_ENUM } from '../lib/roles'

interface ToastMsg { id:number; text:string; tone:'success'|'info'|'error' }
interface StoreState {
 loaded:boolean; roomTypes:RoomType[]; rooms:Room[]; bookings:Booking[]; customers:Customer[]; staff:StaffMember[]; menuItems:MenuItem[]; drinks:Drink[]; shortLets:ShortLet[]; events:EventItem[]; maintenanceTickets:MaintenanceTicket[]; housekeepingTasks:HousekeepingTask[]; billboards:BillboardSpace[]; payments:Payment[]; offers:Offer[]; guestRequests:GuestRequest[]; parkingZones:ParkingZone[]; galleryImages:GalleryImage[]; amenities:Amenity[]; toasts:ToastMsg[]
 loadAll:()=>Promise<void>; pushToast:(text:string,tone?:ToastMsg['tone'])=>void; dismissToast:(id:number)=>void
 updateRoomTypePrice:(id:string,price:number)=>void; toggleRoomTypeActive:(id:string)=>void; addRoomType:(rt:RoomType)=>void; setRoomStatus:(roomId:string,status:RoomStatus)=>void
 createBooking:(b:Omit<Booking,'id'|'reference'|'createdAt'|'status'|'paymentStatus'>)=>Booking; confirmBookingPayment:(bookingId:string)=>void; checkInBooking:(bookingId:string,roomId:string)=>void; checkOutBooking:(bookingId:string)=>void; cancelBooking:(bookingId:string)=>void
 markCleaningStarted:(taskId:string)=>void; markCleaned:(taskId:string,cleanerName:string)=>void
 addMaintenanceTicket:(t:Omit<MaintenanceTicket,'id'|'status'>)=>void; resolveMaintenanceTicket:(id:string)=>void; updateMaintenanceTicket:(id:string,patch:Partial<MaintenanceTicket>)=>void
 updateMenuItemPrice:(id:string,price:number)=>void; toggleMenuItemAvailable:(id:string)=>void; addMenuItem:(item:MenuItem)=>void; updateMenuItem:(id:string,patch:Partial<MenuItem>)=>void; deleteMenuItem:(id:string)=>void
 updateDrinkPrice:(id:string,price:number)=>void; toggleDrinkAvailable:(id:string)=>void; addDrink:(d:Drink)=>void; deleteDrink:(id:string)=>void
 addStaff:(s:StaffMember)=>void; toggleStaffStatus:(id:string)=>void; updateStaffRole:(id:string,role:StaffMember['role'])=>void; updateStaffInfo:(id:string,updates:Partial<Pick<StaffMember,'name'|'phone'|'department'>>)=>void
 togglePublishEvent:(id:string)=>void; addEvent:(e:EventItem)=>void; updateEvent:(id:string,patch:Partial<EventItem>)=>void; deleteEvent:(id:string)=>void
 toggleOfferActive:(id:string)=>void; addOffer:(o:Offer)=>void; updateOffer:(id:string,patch:Partial<Offer>)=>void; deleteOffer:(id:string)=>void
 addShortLet:(sl:ShortLet)=>void; updateShortLet:(id:string,patch:Partial<ShortLet>)=>void; toggleShortLetAvailable:(id:string)=>void; deleteShortLet:(id:string)=>void
 addBillboard:(b:BillboardSpace)=>void; updateBillboard:(id:string,patch:Partial<BillboardSpace>)=>void; toggleBillboardAvailable:(id:string)=>void; deleteBillboard:(id:string)=>void
 addGuestRequest:(r:{customerId?:string;bookingRef?:string;room?:string;guestName:string;type:string;message:string})=>void; resolveGuestRequest:(id:string)=>void
 addGalleryImage:(url:string,caption?:string)=>void; removeGalleryImage:(id:string)=>void; setRoomTypeImages:(id:string,images:string[])=>void; saveAmenity:(key:string,patch:Partial<Amenity>)=>Promise<boolean>
}
let toastSeq=1
async function save(table:string,patch:Record<string,any>,id:string){const{error}=await supabase.from(table).update(patch).eq('id',id);if(error)console.error(`[${table}] update failed`,error.message)}
async function insertRow(table:string,row:Record<string,any>){const{error}=await supabase.from(table).insert(row);if(error)console.error(`[${table}] insert failed`,error.message)}
async function deleteRow(table:string,id:string){const{error}=await supabase.from(table).delete().eq('id',id);if(error)console.error(`[${table}] delete failed`,error.message)}

export const useStore=create<StoreState>((set,get)=>({
 loaded:false,roomTypes:[],rooms:[],bookings:[],customers:[],staff:[],menuItems:[],drinks:[],shortLets:[],events:[],maintenanceTickets:[],housekeepingTasks:[],billboards:[],payments:[],offers:[],guestRequests:[],parkingZones:[],galleryImages:[],amenities:[],toasts:[],
 loadAll:async()=>{
  const [rt,rm,bk,cu,st,mi,dr,sl,ev,mt,hk,bb,pz,pay,of,gr,gi,am]=await Promise.all([
   supabase.from('room_types').select('*').order('price'),supabase.from('rooms').select('*').order('room_number'),supabase.from('bookings').select('*').order('created_at',{ascending:false}),supabase.from('customers').select('*').order('name'),supabase.from('staff').select('*').order('name'),supabase.from('menu_items').select('*').order('name'),supabase.from('drinks').select('*').order('name'),supabase.from('short_lets').select('*').order('price'),supabase.from('events').select('*').order('date'),supabase.from('maintenance_tickets').select('*').order('date_reported',{ascending:false}),supabase.from('housekeeping_tasks').select('*').order('room'),supabase.from('billboards').select('*').order('price',{ascending:false}),supabase.from('parking_zones').select('*').order('name'),supabase.from('payments').select('*').order('date',{ascending:false}),supabase.from('offers').select('*').order('title'),supabase.from('guest_requests').select('*').order('created_at',{ascending:false}),supabase.from('gallery_images').select('*').order('sort_order'),supabase.from('amenities').select('*').order('name')
  ])
  set({loaded:true,roomTypes:(rt.data??[]).map(mapRoomType),rooms:(rm.data??[]).map(mapRoom),bookings:(bk.data??[]).map(mapBooking),customers:(cu.data??[]).map(mapCustomer),staff:(st.data??[]).map(mapStaff),menuItems:(mi.data??[]).map(mapMenuItem),drinks:(dr.data??[]).map(mapDrink),shortLets:(sl.data??[]).map(mapShortLet),events:(ev.data??[]).map(mapEvent),maintenanceTickets:(mt.data??[]).map(mapMaintenanceTicket),housekeepingTasks:(hk.data??[]).map(mapHousekeepingTask),billboards:(bb.data??[]).map(mapBillboard),parkingZones:(pz.data??[]).map(mapParkingZone),payments:(pay.data??[]).map(mapPayment),offers:(of.data??[]).map(mapOffer),guestRequests:(gr.data??[]).map(mapGuestRequest),galleryImages:(gi.data??[]).map(mapGalleryImage),amenities:(am.data??[]).map(mapAmenity)})
 },
 pushToast:(text,tone='success')=>{const id=toastSeq++;set(s=>({toasts:[...s.toasts,{id,text,tone}]}));setTimeout(()=>get().dismissToast(id),3600)},dismissToast:id=>set(s=>({toasts:s.toasts.filter(t=>t.id!==id)})),
 updateRoomTypePrice:(id,price)=>{set(s=>({roomTypes:s.roomTypes.map(rt=>rt.id===id?{...rt,price}:rt)}));save('room_types',{price},id);get().pushToast('Price updated — now live on the public website','success')},
 toggleRoomTypeActive:id=>{const next=!get().roomTypes.find(rt=>rt.id===id)?.active;set(s=>({roomTypes:s.roomTypes.map(rt=>rt.id===id?{...rt,active:next}:rt)}));save('room_types',{active:next},id);get().pushToast('Room availability toggled','info')},
 addRoomType:rt=>{set(s=>({roomTypes:[rt,...s.roomTypes]}));insertRow('room_types',{id:rt.id,slug:rt.slug,name:rt.name,price:rt.price,guests:rt.guests,bed_type:rt.bedType,size_sqm:rt.sizeSqm,amenities:rt.amenities,images:rt.images,description:rt.description,active:rt.active});get().pushToast('Room type added','success')},
 setRoomStatus:(roomId,status)=>{set(s=>({rooms:s.rooms.map(r=>r.id===roomId?{...r,status}:r)}));save('rooms',{status},roomId)},
 createBooking:b=>{const reference=`BPH-${Math.floor(24900+Math.random()*900)}`;const booking:Booking={...b,id:`b_${Date.now()}`,reference,createdAt:new Date().toISOString().slice(0,10),status:'pending',paymentStatus:'pending'};set(s=>({bookings:[booking,...s.bookings]}));insertRow('bookings',{id:booking.id,reference,customer_id:booking.customerId,room_type_id:booking.roomTypeId,room_id:booking.roomId??null,check_in:booking.checkIn,check_out:booking.checkOut,adults:booking.adults,children:booking.children,amount:booking.amount,payment_status:'pending',status:'pending',special_requests:booking.specialRequests??null});return booking},
 confirmBookingPayment:bookingId=>{const booking=get().bookings.find(b=>b.id===bookingId);set(s=>({bookings:s.bookings.map(b=>b.id===bookingId?{...b,status:'confirmed',paymentStatus:'paid'}:b)}));save('bookings',{status:'confirmed',payment_status:'paid'},bookingId);if(booking?.roomId)window.dispatchEvent(new CustomEvent('bluepair:database-change',{detail:{table:'bookings',operation:'UPDATE',roomId:booking.roomId,status:'paid'}}));if(booking&&!get().payments.some(p=>p.bookingRef===booking.reference)){const customerName=get().customers.find(c=>c.id===booking.customerId)?.name??'Guest';const paidOn=new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Lagos'});const payment:Payment={id:`pay_${Date.now()}`,reference:`INV-${booking.reference.replace(/^BPH-/,'')}`,bookingRef:booking.reference,customer:customerName,amount:booking.amount,method:'Paystack',status:'success',date:paidOn};set(s=>({payments:[payment,...s.payments]}));insertRow('payments',{id:payment.id,reference:payment.reference,booking_ref:payment.bookingRef,customer:payment.customer,customer_id:booking.customerId,amount:payment.amount,method:payment.method,status:payment.status,date:payment.date})}},
 checkInBooking:(bookingId,roomId)=>{set(s=>({bookings:s.bookings.map(b=>b.id===bookingId?{...b,status:'checked_in',roomId}:b)}));save('bookings',{status:'checked_in',room_id:roomId},bookingId)},
 checkOutBooking:bookingId=>{const booking=get().bookings.find(b=>b.id===bookingId);set(s=>({bookings:s.bookings.map(b=>b.id===bookingId?{...b,status:'checked_out'}:b)}));save('bookings',{status:'checked_out'},bookingId);if(booking?.roomId)window.dispatchEvent(new CustomEvent('bluepair:database-change',{detail:{table:'room_daily_statuses',operation:'UPDATE',roomId:booking.roomId,status:'cleaning_required'}}))},
 cancelBooking:bookingId=>{const booking=get().bookings.find(b=>b.id===bookingId);set(s=>({bookings:s.bookings.map(b=>b.id===bookingId?{...b,status:'cancelled'}:b)}));save('bookings',{status:'cancelled'},bookingId);if(booking?.roomId)window.dispatchEvent(new CustomEvent('bluepair:database-change',{detail:{table:'bookings',operation:'UPDATE',roomId:booking.roomId,status:'cancelled'}}))},
 markCleaningStarted:taskId=>{const task=get().housekeepingTasks.find(t=>t.id===taskId);set(s=>({housekeepingTasks:s.housekeepingTasks.map(t=>t.id===taskId?{...t,status:'in_progress'}:t)}));save('housekeeping_tasks',{status:'in_progress'},taskId);if(task){const room=get().rooms.find(r=>r.roomNumber===task.room);if(room)window.dispatchEvent(new CustomEvent('bluepair:database-change',{detail:{table:'room_daily_statuses',operation:'UPDATE',roomId:room.id,status:'cleaning'}}))}},
 markCleaned:(taskId,cleanerName)=>{const task=get().housekeepingTasks.find(t=>t.id===taskId);set(s=>({housekeepingTasks:s.housekeepingTasks.map(t=>t.id===taskId?{...t,status:'completed',assignedTo:cleanerName,completedAt:new Date().toISOString()}:t)}));save('housekeeping_tasks',{status:'completed',assigned_to:cleanerName,completed_at:new Date().toISOString()},taskId);if(task){const room=get().rooms.find(r=>r.roomNumber===task.room);if(room)window.dispatchEvent(new CustomEvent('bluepair:database-change',{detail:{table:'room_daily_statuses',operation:'UPDATE',roomId:room.id,status:'available'}}))}},
 addMaintenanceTicket:t=>{const id=`mt_${Date.now()}`;const row={id,room:t.room,issue:t.issue,priority:t.priority,assigned_to:t.assignedTo,date_reported:t.dateReported,status:'open',notes:t.notes};set(s=>({maintenanceTickets:[{...t,id,status:'open'},...s.maintenanceTickets]}));insertRow('maintenance_tickets',row)},
 resolveMaintenanceTicket:id=>{set(s=>({maintenanceTickets:s.maintenanceTickets.map(t=>t.id===id?{...t,status:'resolved'}:t)}));save('maintenance_tickets',{status:'resolved'},id)},
 updateMaintenanceTicket:(id,patch)=>{set(s=>({maintenanceTickets:s.maintenanceTickets.map(t=>t.id===id?{...t,...patch}:t)}));const dbPatch:any={};if(patch.assignedTo!==undefined)dbPatch.assigned_to=patch.assignedTo;if(patch.priority!==undefined)dbPatch.priority=patch.priority;if(patch.status!==undefined)dbPatch.status=patch.status;if(patch.notes!==undefined)dbPatch.notes=patch.notes;save('maintenance_tickets',dbPatch,id)},
 updateMenuItemPrice:(id,price)=>{set(s=>({menuItems:s.menuItems.map(x=>x.id===id?{...x,price}:x)}));save('menu_items',{price},id)},toggleMenuItemAvailable:id=>{const n=!get().menuItems.find(x=>x.id===id)?.available;set(s=>({menuItems:s.menuItems.map(x=>x.id===id?{...x,available:n}:x)}));save('menu_items',{available:n},id)},addMenuItem:item=>{set(s=>({menuItems:[item,...s.menuItems]}));insertRow('menu_items',{id:item.id,outlet:item.outlet,category:item.category,name:item.name,price:item.price,image:item.image,available:item.available})},updateMenuItem:(id,patch)=>{set(s=>({menuItems:s.menuItems.map(x=>x.id===id?{...x,...patch}:x)}));const p:any={};Object.entries(patch).forEach(([k,v])=>p[k]=v);save('menu_items',p,id)},deleteMenuItem:id=>{set(s=>({menuItems:s.menuItems.filter(x=>x.id!==id)}));deleteRow('menu_items',id)},
 updateDrinkPrice:(id,price)=>{set(s=>({drinks:s.drinks.map(x=>x.id===id?{...x,price}:x)}));save('drinks',{price},id)},toggleDrinkAvailable:id=>{const n=!get().drinks.find(x=>x.id===id)?.available;set(s=>({drinks:s.drinks.map(x=>x.id===id?{...x,available:n}:x)}));save('drinks',{available:n},id)},addDrink:d=>{set(s=>({drinks:[d,...s.drinks]}));insertRow('drinks',{id:d.id,bar:d.bar,category:d.category,name:d.name,price:d.price,available:d.available})},deleteDrink:id=>{set(s=>({drinks:s.drinks.filter(x=>x.id!==id)}));deleteRow('drinks',id)},
 addStaff:s=>{set(x=>({staff:[s,...x.staff]}));insertRow('staff',{id:s.id,user_id:s.userId??null,name:s.name,email:s.email,phone:s.phone,role:ROLE_LABEL_TO_ENUM[s.role],department:s.department,status:s.status,joined:s.joined})},toggleStaffStatus:id=>{const n=get().staff.find(s=>s.id===id)?.status==='active'?'disabled':'active';set(s=>({staff:s.staff.map(x=>x.id===id?{...x,status:n}:x)}));save('staff',{status:n},id)},updateStaffRole:(id,role)=>{set(s=>({staff:s.staff.map(x=>x.id===id?{...x,role}:x)}));save('staff',{role:ROLE_LABEL_TO_ENUM[role]},id)},updateStaffInfo:(id,updates)=>{set(s=>({staff:s.staff.map(x=>x.id===id?{...x,...updates}:x)}));const p:any={};if(updates.name!==undefined)p.name=updates.name;if(updates.phone!==undefined)p.phone=updates.phone;if(updates.department!==undefined)p.department=updates.department;save('staff',p,id)},
 togglePublishEvent:id=>{const n=!get().events.find(e=>e.id===id)?.published;set(s=>({events:s.events.map(e=>e.id===id?{...e,published:n}:e)}));save('events',{published:n},id)},addEvent:e=>{set(s=>({events:[e,...s.events]}));insertRow('events',{id:e.id,title:e.title,date:e.date,price:e.price,capacity:e.capacity,image:e.image,description:e.description,published:e.published})},updateEvent:(id,patch)=>{set(s=>({events:s.events.map(e=>e.id===id?{...e,...patch}:e)}));const p:any={};Object.entries(patch).forEach(([k,v])=>p[k]=v);save('events',p,id)},deleteEvent:id=>{set(s=>({events:s.events.filter(e=>e.id!==id)}));deleteRow('events',id)},
 toggleOfferActive:id=>{const next=!get().offers.find(o=>o.id===id)?.active;set(s=>({offers:s.offers.map(o=>o.id===id?{...o,active:next}:o)}));save('offers',{active:next},id)},addOffer:o=>{set(s=>({offers:[o,...s.offers]}));insertRow('offers',{id:o.id,title:o.title,description:o.description,discount:o.discount,category:o.category,active:o.active})},updateOffer:(id,patch)=>{set(s=>({offers:s.offers.map(o=>o.id===id?{...o,...patch}:o)}));const p:any={};Object.entries(patch).forEach(([k,v])=>p[k]=v);save('offers',p,id)},deleteOffer:id=>{set(s=>({offers:s.offers.filter(o=>o.id!==id)}));deleteRow('offers',id)},
 addShortLet:sl=>{set(s=>({shortLets:[sl,...s.shortLets]}));insertRow('short_lets',{id:sl.id,name:sl.name,type:sl.type,price:sl.price,bedrooms:sl.bedrooms,amenities:sl.amenities,image:sl.image,available:sl.available,description:sl.description})},updateShortLet:(id,patch)=>{set(s=>({shortLets:s.shortLets.map(x=>x.id===id?{...x,...patch}:x)}));const p:any={};Object.entries(patch).forEach(([k,v])=>p[k]=v);save('short_lets',p,id)},toggleShortLetAvailable:id=>{const next=!get().shortLets.find(x=>x.id===id)?.available;set(s=>({shortLets:s.shortLets.map(x=>x.id===id?{...x,available:next}:x)}));save('short_lets',{available:next},id)},deleteShortLet:id=>{set(s=>({shortLets:s.shortLets.filter(x=>x.id!==id)}));deleteRow('short_lets',id)},
 addBillboard:b=>{set(s=>({billboards:[b,...s.billboards]}));insertRow('billboards',{id:b.id,location:b.location,dimensions:b.dimensions,price:b.price,image:b.image,available:b.available})},updateBillboard:(id,patch)=>{set(s=>({billboards:s.billboards.map(b=>b.id===id?{...b,...patch}:b)}));const p:any={};Object.entries(patch).forEach(([k,v])=>p[k]=v);save('billboards',p,id)},toggleBillboardAvailable:id=>{const next=!get().billboards.find(b=>b.id===id)?.available;set(s=>({billboards:s.billboards.map(b=>b.id===id?{...b,available:next}:b)}));save('billboards',{available:next},id)},deleteBillboard:id=>{set(s=>({billboards:s.billboards.filter(b=>b.id!==id)}));deleteRow('billboards',id)},
 addGuestRequest:r=>{const id=`gr_${Date.now()}`;const item:GuestRequest={id,customerId:r.customerId,bookingRef:r.bookingRef??'',room:r.room??'',guestName:r.guestName,type:r.type,message:r.message,status:'open',createdAt:new Date().toISOString().slice(0,10)};set(s=>({guestRequests:[item,...s.guestRequests]}));insertRow('guest_requests',{id,customer_id:r.customerId??null,booking_ref:r.bookingRef??null,room:r.room??null,guest_name:r.guestName,type:r.type,message:r.message,status:'open'})},resolveGuestRequest:id=>{set(s=>({guestRequests:s.guestRequests.map(r=>r.id===id?{...r,status:'resolved'}:r)}));save('guest_requests',{status:'resolved'},id)},
 addGalleryImage:(url,caption)=>{const id=`gi_${Date.now()}`;const image={id,url,caption,sortOrder:get().galleryImages.length};set(s=>({galleryImages:[...s.galleryImages,image]}));insertRow('gallery_images',{id,url,caption:caption??null,sort_order:image.sortOrder})},removeGalleryImage:id=>{set(s=>({galleryImages:s.galleryImages.filter(x=>x.id!==id)}));deleteRow('gallery_images',id)},setRoomTypeImages:(id,images)=>{set(s=>({roomTypes:s.roomTypes.map(rt=>rt.id===id?{...rt,images}:rt)}));save('room_types',{images},id)},saveAmenity:async(key,patch)=>{const dbPatch:any={};if(patch.name!==undefined)dbPatch.name=patch.name;if(patch.eyebrow!==undefined)dbPatch.eyebrow=patch.eyebrow;if(patch.description!==undefined)dbPatch.description=patch.description;if(patch.heroImage!==undefined)dbPatch.hero_image=patch.heroImage;if(patch.gallery!==undefined)dbPatch.gallery=patch.gallery;if(patch.hours!==undefined)dbPatch.hours=patch.hours;if(patch.facilities!==undefined)dbPatch.facilities=patch.facilities;if(patch.pricingNote!==undefined)dbPatch.pricing_note=patch.pricingNote;if(patch.ctaLabel!==undefined)dbPatch.cta_label=patch.ctaLabel;if(patch.published!==undefined)dbPatch.published=patch.published;const{error}=await supabase.from('amenities').update(dbPatch).eq('key',key);if(error)return false;set(s=>({amenities:s.amenities.map(a=>a.key===key?{...a,...patch}:a)}));return true}
}))
