import 'server-only'
import { createClient } from '@supabase/supabase-js'
import { SUPABASE_URL } from './supabase/config'

const SUPABASE_ADMIN_KEY = process.env.SUPABASE_SECRET_KEY ?? process.env.SUPABASE_SERVICE_ROLE_KEY ?? ''
const MAP:Array<[string,string]>=[['/api/admin/paystack','payments'],['/api/paystack','payments'],['/api/payments','payments'],['/api/booking','bookings'],['/api/bookings','bookings'],['/api/availability','availability'],['/api/auth','auth'],['/api/reviews','reviews'],['/api/restaurant','restaurant'],['/api/menu','restaurant'],['/api/bar','bar'],['/api/drinks','bar'],['/api/shortlet','shortlets'],['/api/shortlets','shortlets'],['/api/events','events'],['/api/ai','ai'],['/api/email','emails']]
function env(){if(process.env.VERCEL_ENV==='preview')return 'preview';if(process.env.VERCEL_ENV==='production')return 'production';return process.env.NODE_ENV==='development'?'development':'production'}
export function featureForApiPath(path:string){return MAP.find(([p])=>path===p||path.startsWith(p+'/'))?.[1]??null}
export async function getApiFeatureStatus(path:string){const feature=featureForApiPath(path);if(!feature)return {enabled:true,feature:null};if(!SUPABASE_ADMIN_KEY){console.error('[developer-feature-controls][config] Missing SUPABASE_SECRET_KEY/SUPABASE_SERVICE_ROLE_KEY');return {enabled:true,feature}}const db=createClient(SUPABASE_URL,SUPABASE_ADMIN_KEY,{auth:{autoRefreshToken:false,persistSession:false}});const {data,error}=await db.from('developer_feature_controls').select('feature,enabled').eq('environment',env()).in('feature',['all_apis',feature]);if(error){console.error('[developer-feature-controls][read]',error.message);return {enabled:true,feature}}const all=data?.find(r=>r.feature==='all_apis');const specific=data?.find(r=>r.feature===feature);return {enabled:all?.enabled!==false&&specific?.enabled!==false,feature}}
