'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { supabase } from '../../../lib/supabase/client'
import { Loader2, LockKeyhole } from 'lucide-react'

export default function ResetPasswordPage() {
  const router = useRouter(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [ready, setReady] = useState(false); const [loading, setLoading] = useState(false); const [checking, setChecking] = useState(true); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState(false)
  useEffect(() => { let active = true; supabase.auth.getSession().then(({ data }) => { if (!active) return; setReady(!!data.session); setChecking(false) }); const { data: listener } = supabase.auth.onAuthStateChange((event, session) => { if (!active) return; if (event === 'PASSWORD_RECOVERY' || session) setReady(true) }); return () => { active = false; listener.subscription.unsubscribe() } }, [])
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(null); if (password.length < 6) { setError('Password must be at least 6 characters.'); return } if (password !== confirm) { setError('Passwords do not match.'); return } setLoading(true); const { error } = await supabase.auth.updateUser({ password }); setLoading(false); if (error) { setError(error.message); return } setSuccess(true); window.setTimeout(() => { router.push('/account/login'); router.refresh() }, 1400) }
  return <div className="min-h-screen flex items-center justify-center bg-navy-950 px-5 py-12"><div className="w-full max-w-sm bg-white rounded-xl2 shadow-pop p-7 sm:p-8"><div className="flex justify-center mb-5"><img src="/icon-192.png" alt="Blue Pair Hotel" className="w-16 h-16 sm:w-[72px] sm:h-[72px] rounded-2xl object-cover" /></div><p className="text-sm text-navy-400 mb-7 text-center">Choose a new password for your guest account</p>{checking ? <div className="py-8 flex justify-center text-navy-400"><Loader2 size={22} className="animate-spin" /></div> : success ? <div className="text-center py-4"><div className="w-12 h-12 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center mx-auto mb-4"><LockKeyhole size={21} /></div><h2 className="font-display text-lg font-semibold mb-2">Password updated</h2><p className="text-sm text-navy-500">Your password has been changed. Taking you back to sign in…</p></div> : !ready ? <div className="text-center"><p className="text-sm text-navy-500 leading-relaxed">This password reset link is invalid, expired, or has already been used.</p><Link href="/account/forgot-password" className="btn-primary w-full justify-center mt-6">Request a new link</Link></div> : <form onSubmit={submit}>{error && <div className="mb-4 text-xs font-medium text-red-600 bg-red-50 rounded-lg px-3.5 py-2.5">{error}</div>}<label className="field-label">New password</label><input type="password" required minLength={6} autoComplete="new-password" value={password} onChange={e => setPassword(e.target.value)} className="field-input mb-4" placeholder="At least 6 characters" /><label className="field-label">Confirm new password</label><input type="password" required minLength={6} autoComplete="new-password" value={confirm} onChange={e => setConfirm(e.target.value)} className="field-input mb-5" placeholder="Repeat your password" /><button type="submit" disabled={loading} className="btn-primary w-full justify-center disabled:opacity-60 flex items-center gap-2">{loading && <Loader2 size={15} className="animate-spin" />}{loading ? 'Updating…' : 'Update password'}</button></form>}</div></div>
}
