'use client'
import { useEffect, useState } from 'react'
import { CalendarDays, Loader2 } from 'lucide-react'
import { addDaysISO, todayISO } from '../../lib/format'
import { useStore } from '../../store/useStore'
const COLORS:Record<string,string>={available:'bg-emerald-500',cleaning_required:'bg-amber-300 text-navy-950',cleaning:'bg-amber-400 text-navy-950',maintenance:'bg-orange-500',taken:'bg-red-600',held:'bg-amber-400 text-navy-950',availableSoon:'bg-gold-500 text-navy-950',available_soon:'bg-gold-500 text-navy-950'}
const LABELS:Record<string,string>={available:'Available',cleaning_required:'Cleaning Required',cleaning:'Cleaning',maintenance:'Maintenance',taken:'Taken',held:'Payment Hold',availableSoon:'Available Soon',available_soon:'Available Soon'}
export default function AvailabilityGrid({onSelect}:{onSelect?:(roomId:string)=>void}){
 const {rooms}=useStore(); const [date,setDate]=useState(todayISO()); const [live,setLive]=useState<Record<string,string>>({}); const [loading,setLoading]=useState(false)
 useEffect(()=>{ if(!date){setLive({});return} let cancelled=false; setLoading(true); const checkOut=addDaysISO(1,date); const url=`/api/public/availability?checkin=${encodeURIComponent(date)}&checkout=${encodeURIComponent(checkOut)}`; console.info('[admin-availability][request]',{url,date,checkOut,roomCount:rooms.length}); fetch(url,{cache:'no-store'}).then(async r=>{const data=await r.json().catch(()=>null);console.info('[admin-availability][response]',{ok:r.ok,status:r.status,date,roomCount:data?.rooms?.length??0,error:data?.error??null});return r.ok?data:null}).then(data=>{if(cancelled)return;const next:Record<string,string>={};for(const r of data?.rooms||[])next[r.id]=r.admin_status||r.guest_status;console.info('[admin-availability][mapped]',{date,states:Object.values(next).reduce((a:string,s)=>({...a,[s]:(a[s]||0)+1}),{})});setLive(next)}).catch(error=>{console.error('[admin-availability][error]',{date,error});if(!cancelled)setLive({})}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[date,rooms.length])
 return <div><div className="rounded-md bg-cream-100 border border-black/[.06] p-4 mb-5"><div className="flex items-center gap-2 mb-3"><CalendarDays size={15} className="text-gold-600"/><div><p className="text-xs font-semibold">Room status for this day</p><p className="text-[10px] text-navy-400">Each room card shows what is happening on the selected date. Reservations use 3:00 PM check-in and 12:00 PM check-out.</p></div>{loading&&<Loader2 size={13} className="ml-auto animate-spin text-navy-400"/>}</div><div><label className="field-label">Date</label><input type="date" min={todayISO()} value={date} onChange={e=>setDate(e.target.value)} className="field-input"/></div></div><div className="flex flex-wrap gap-4 mb-5 text-xs text-navy-500">{['available','taken','cleaning_required','cleaning','maintenance','available_soon'].map(k=><span key={k} className="flex items-center gap-1.5"><i className={'w-2.5 h-2.5 rounded-sm inline-block '+COLORS[k]} />{LABELS[k]}</span>)}</div><div className="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 gap-2.5">{rooms.map(r=>{const state=live[r.id]||r.status;return <button key={r.id} onClick={()=>onSelect?.(r.id)} title={`Room ${r.roomNumber} · ${LABELS[state]||state}`} className={'aspect-square rounded-md flex flex-col items-center justify-center text-white font-bold text-xs gap-0.5 hover:brightness-110 transition '+(COLORS[state]||COLORS.available)}><span>{r.roomNumber}</span><span className="text-[8px] font-medium opacity-80">{LABELS[state]||state}</span></button>})}</div><p className="text-[10px] text-navy-400 mt-4">Selected date: <b>{date}</b>. Click a room for operational controls.</p></div>
}