-- Date-specific room operations. The physical rooms.status remains the long-lived
-- operational state (maintenance is the only indefinite block). Daily states are
-- used for cleaning/available-soon/available and are evaluated only for that date.
create table if not exists public.room_daily_statuses (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(id) on delete cascade,
  status text not null check (status in ('available','cleaning_required','cleaning','available_soon')),
  status_date date not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(room_id,status_date)
);
create index if not exists room_daily_statuses_date_idx on public.room_daily_statuses(status_date,room_id);

drop trigger if exists booking_room_lifecycle_trigger on public.bookings;
drop trigger if exists housekeeping_room_lifecycle_trigger on public.housekeeping_tasks;

create or replace function public.sync_booking_room_lifecycle()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.status = 'checked_out' and new.room_id is not null then
    insert into public.room_daily_statuses(room_id,status,status_date,notes,updated_at)
    values(new.room_id,'cleaning_required',coalesce(new.checked_out_at::date,current_date),'Guest checked out; cleaning required.',now())
    on conflict(room_id,status_date) do update set status='cleaning_required',notes=excluded.notes,updated_at=now();
    update public.rooms set status='available' where id=new.room_id and status <> 'maintenance';
  end if;
  return new;
end; $$;
create trigger booking_room_lifecycle_trigger
after update of status,checked_out_at on public.bookings
for each row execute function public.sync_booking_room_lifecycle();

create or replace function public.sync_housekeeping_room_lifecycle()
returns trigger language plpgsql security definer set search_path=public as $$
declare d date := current_date;
begin
  if new.room_id is null then return new; end if;
  if new.status = 'in_progress' then
    insert into public.room_daily_statuses(room_id,status,status_date,notes,updated_at)
    values(new.room_id,'cleaning',d,'Housekeeping in progress.',now())
    on conflict(room_id,status_date) do update set status='cleaning',notes=excluded.notes,updated_at=now();
    update public.rooms set status='available' where id=new.room_id and status <> 'maintenance';
  elsif new.status = 'completed' then
    insert into public.room_daily_statuses(room_id,status,status_date,notes,updated_at)
    values(new.room_id,'available',d,'Housekeeping completed.',now())
    on conflict(room_id,status_date) do update set status='available',notes=excluded.notes,updated_at=now();
    update public.rooms set status='available' where id=new.room_id and status <> 'maintenance';
  end if;
  return new;
end; $$;
create trigger housekeeping_room_lifecycle_trigger
after update of status on public.housekeeping_tasks
for each row execute function public.sync_housekeeping_room_lifecycle();

comment on table public.room_daily_statuses is 'Date-specific operational room state. Maintenance remains on rooms.status and is indefinite.';
